language: node_js
node_js:
- '16'
services:
- mongodb
notifications:
  email: false
  slack:
    rooms:
      secure: M7YNWckJLxcqMUJ2yhP648eYzhBSbUhai3VvVyFYvUjNbUgWWuMtCJSV9RGN95cvVHYzVSnfk4vMMdQ64ddrbK8uTa7lvksp+mqqEBn73tK7E7wP2GF5MwiyDKzoExaU1Ux1MBzIbFYahudmbF860lBq2FgsnnwquzJWGly6A4Dk+YO9SYk0n0+EKsPkCO9rzrViITrXuTJ8hcnszogsRUuxSqXufgCgW29HGQVh7aF2iqV5s2L2kCeTpzQBDIj014PPoIEsu/hOgzrf/fOHsr/bkzyg8EtdqWSZ1fakFOL5tGcVD/2gEnzvNO/y/kGYUMH+DIG5ASYODeVCKMmLaBcH9BNPi0YUoEJDxd3Oev5SeIj4N8PrsgCotN/fBZD1QlTGUe5Dn35acThMoqb5x8PqZ99qCAuF4vGYmkQNcqH/FYNssk6JxRmufaak5LSnvcBFPkvvnCWYQ45JtbWA3A0AgIwCLRzr6kAe7bLTELyU2hT6u5Vq7tsSwa1mhs+xtiTpVUQFGG5pkwwSJBn+K7WLIOCvhQv8HvUoBrJJhOI/V6FxoQRoTVDHP3bkTogjkrKlrTyQ7FGlmvhAiBx6UsRoKPmj7jmsDBmjkx+l9OAZeV3cvSaVTiqCr5OlxCKwo7j3zY309PJ92PoavzHpJ/4tNrIjeP7qyHKlwCHIbnc=
    on_success: always
    on_failure: always
env:
- CC_TEST_REPORTER_ID=8b94ba90d9b5d20c6c06e3c9c2c126c14d904bbab5b6b7086dd4d891da6b112a
before-script:
# codeclimate
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
# development secrets
- git clone https://oauth2:$GITHUB_TOKEN@github.com/kalisio/development.git development
- source development/workspaces/libs/libs.sh feathers-import-export
# feathers-s3
- git clone https://oauth2:$GITHUB_TOKEN@github.com/kalisio/feathers-s3 feathers-s3
- cd feathers-s3 && yarn && yarn link
- cd .. && yarn link @kalisio/feathers-s3
script:
- export DEBUG="feathers-import-export:export"
- yarn test
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
